### ISSUE TITLE
Missing Textures and Materials folder prevents using the dialog

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/ArtOfIllusion#101]
Hi.

I noticed that the TexturesAndMaterialDialog fails to open if the assetsFolder is missing. Line 204 reports nullPointerExceptipn. As you can launch AoI without the Plugins folder I think it'd be rasonable to be able to open the dialog too without the folder present and use it to manage the textures and materials that are there. 

One approach could be that the missing folder would be created at dialog launch or at least if the user chooses to export any materals or textures.

**Comment by Sailsman63** [comment]
Question: How do you end up with a build without `Textures and Materials` pre-generated? The core build script creates it during the build process, and any installed version should have it provided by the installer...

**Comment by peteihis** [comment]
Hmm.... Turns out I have been using the ArtOfIllusion.xml instead of build.xml.... I just copied the lib-folder under Live_Application for the .jar to run.

**Comment by Sailsman63** [comment]
Yeah, you need to run the `build.xml` *once* when you first start building. Just `ant`. If you want to see some of the cool new stuff, try `ant help`
