### ISSUE TITLE
OSSpecific plugin can't run with JDK9+

### ISSUE THREAD

**Issue by makiam** [ArtOfIllusion/ArtOfIllusion#118]
running OSSpecific plugin with JDK9+ gives an exception in app log:
java.lang.NoSuchMethodException: com.apple.eawt.Application.setEnabledAboutMenu(boolean)

Such methods are no more available.
Oracle recommends to use instead java.awt.Desktop class but this affects backward compatibility with older java versions

**Comment by Sailsman63** [comment]
Huh... Wonder how it compiles on Java 9+, then? I'll take a closer look, perhaps catch the exception & then try the desktop method?

**Comment by Sailsman63** [comment]
@peastman can you confirm this issue? Maksim is the only one who seems to have run across it...

**Comment by peastman** [comment]
Yes, I can confirm this happens.  It looks like they got rid of platform-specific APIs like this and introduced cross platform replacements for them.  So we'll need to use different mechanisms depending on the Java version.

http://openjdk.java.net/jeps/272
https://docs.oracle.com/javase/9/docs/api/java/awt/Desktop.html

**Comment by Sailsman63** [comment]
Thanks!

@makiam I see that you posted a compiled copy of the plugin with a fix. Can we see the code?

**Comment by makiam** [comment]
#165
