### ISSUE TITLE
Coortinates in Camera view / 3.1.0-beta1

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/ArtOfIllusion#121]
Coordinates are changing size in camera views, when using center-click fit in 3.1.0-beta1.

This does not happen with the version in my repository nor does it happen with an entirely new clone of the ArtOfIllusion master. 

![ZoomToSphere](https://user-images.githubusercontent.com/22843957/59402281-48fae300-8da6-11e9-821f-42109e3220bd.jpg)
![ZoomToCube](https://user-images.githubusercontent.com/22843957/59402286-4ac4a680-8da6-11e9-8352-68ec171f7f63.jpg)

You can find a screen capture video in https://sourceforge.net/p/aoi/discussion/47782/thread/eaea857da7/?page=1&limit=25#973f

**Comment by Sailsman63** [comment]
I was not able to duplicate this at all, even with a fresh download from the release page. In reviewing your video further, it seems you have some sort of mixed-up build. (_Not_ the actual release) The version number comes from the current source, but the copyright date (found in `artofillusion.TitleWindow`) dates back to the 2.4/2.5 era. Who knows when other files were from?

I've just uploaded beta 2, so should be a moot point.

**Comment by peteihis** [comment]
OK.... My mistake. But a weird one.

The ArtOfIllusion.jar _is_ the actual downloaded 3.1.0-beta but I had copied plugins from an old setup. What you see on the video is not the the TitleWindow it is the About window of the Help-plugin, which I, of course, did not mean to copy but obviously did. The Help, that came with the beta1 still says 2008 whereas the title window says 2015.

But then I can not imagine, what could have caused the coordinates to resize... I _thought_ I removed all my own experiments but, ehh.... If this pops up again I'll let you know.

**Comment by peteihis** [comment]
Root cause:

Perspective setting of the view happens through the `ViewerPerspectiveControl`, which reads the setting from `SceneCamera` when one is present. Now `DisplayModeIcons` replaces the VPC by it's own control which does not have that functionality. Clearly this is a job ,that should not belong to the perspective control widget, but there are a few pretty tricky interactions between `Camera`, `SceneCamera` and `ViewerCanvas` that currently don't work in a very sensible manner. Hence the arrangement.

I'm hoping to rework the SceneCamera perspective/parallel switching in the nearish future, but for the time being I thing the fastest way forward is to replicate the functionality VPC in DMI.

The current DMI code can be found in http://kuukahvila.com/peteihis/AOI/development/displaymodeicons/ . I think it could be put to the aoisp-code repository as it is, because it is the code that available .jar is made of. -- Then I'd suggest that I'd do the necessary updates and it could be added to GitHub.

**Comment by Sailsman63** [comment]
Looks like a we actually have the full build history in svn. I'll clone it later.

**Comment by makiam** [comment]
Do we need also clone Buoy library to AOI project?

**Comment by peteihis** [comment]
> Looks like a we actually have the full build history in svn

No we don't. In https://sourceforge.net/projects/aoisp/files/ the code version is from 2009. The one we are using was written in 2015 and my assumption was, that the code would have been uploaded to aoisp/files too, but that seems not to have happened.

> Do we need also clone Buoy library to AOI project?

Now that you mention... **buoyx** is nowhere to be found at all.

**Comment by makiam** [comment]
As I understand we have two buoy jars - buoy and buoyx but only one project at SourceForge https://sourceforge.net/projects/buoy/ which contains both parts of code...

**Comment by peteihis** [comment]
Aaargh,,, of course. How did I not think of that? Sorry.

**Comment by Sailsman63** [comment]
`/files` is not the same repository. Look under `/code`.

We do not need to clone the buoy project code, though. It's a stand-alone foundational library, not a plugin. It is not specific to art of illusion.

**Comment by peteihis** [comment]
> Look under `/code`.

My brain needs a holiday from everything. :/
