### ISSUE TITLE
Catch errors during plug-in processing

### ISSUE THREAD

**Issue by Sailsman63** [ArtOfIllusion/ArtOfIllusion#122]
Just found out that a malformed `extensions.xml` from a third party plugin can cause the application to freeze on startup.

`artofillusion.PluginRegistry.processJar` does not catch errors thrown by the classloader code.

Such errors should be logged, but the application should continue to load, possibly with that particular plugin disabled. 

For discussion: what is the proper behavior if a plugin declares several different plugin classes, and only one throws an error?

**Comment by peteihis** [comment]
> For discussion: what is the proper behavior if a plugin declares several different plugin classes, and only one throws an error?

Just out of the blue, early in the morning: If the plugins are independent of each others (like file format translators) the assumption would be "load what you can". If the plugins are more related, like an object and a tool to handle it (not a good example, I admit), then one would be useless without the other.

In the latter case the loaded plugin just would not work but in the first it would seem wrong to block them all. --> I'd say, load what is in tact.

**Comment by Sailsman63** [comment]
Resolved in #78
