### ISSUE TITLE
View tools don't update tool previews

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/ArtOfIllusion#125]
I just noticed, that the mouse view tools (rotate, move, scroll) do not update the previews of Boolean, Extrude, Lathe.... The tools do work but there is a error in the call to view repaint and the effect of the move or rotate will be seen, when the view is updated by something else like a change to the parameters on the dialog.

All the viewtools come with the same basic structure and I copied the same mistake to all of them. Extremely unfortunate, that this got through the betas and all..... Earlier in the process I tried to remember to check all the little views too, but on the last steps I obviously forgot these.

I'll push a fix soon --> 3.1.1 or a "correction package" to 3.1.0?

**Comment by Sailsman63** [comment]
Huh... Wonder what makes them different? I'll take a look.

**Comment by peteihis** [comment]
> Wonder what makes them different?

The view tools are created with an `EditingWindow` as a parameter and in the case of the tool dialogs the parameter is set `null`. There is no reason for the tool dialogs to be editing windows. It would just mean overriding a bunch of unused methods to do nothing. _(To me that would not appear as a good programming practice.)_

In the view tool it just means, that you can't call `theWindow.updateImage()` when theWindow is null. This is how it was coded  before. 

And I know that knew that. :[

<hr>

A different approach might have been to create a more simple interface called, say `EditingDialogHost`, that only contains, what is needed to handle views, and have `EditingWindow`-interface extend that AND have all dialogs that may contain a `ViewerCanvas` implement it AND have the parameter for the tools to be an `EditingDialogHost`. 

Would eventually clarify the structure, removing the need for `!= null`, and moving the separation earlier in the logical chain, which should be a good thing, but it would add another layer to the code structure which already requires (enough of ?) detective work at times .... :/

**Comment by Sailsman63** [comment]
Yeah, I kind of figured that out this morning.
