### ISSUE TITLE
Zero dimension objects cause blank view

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/ArtOfIllusion#126]
It is possible to create primitive objects with at least one input dimension reduced to 0.0. This often happens, when you accidentally click on the view and a creation tool happens to be selected.

There are cases when updateImage of a view gets interrupted because of an object like that, which then leaves the view blank. Unfortunately the blank view will not recover even if the problem object is deleted.

As a correction I see two possibilities: Improve error handling in the view update process or prevent creating zero dimension primitives. I'd go with the latter one. Somehow setting a dimension of an already existing primitive to 0.0 is not a problem. That would seem to imply that a 0.0 dimension at creation actually leaves the primitive faulty in some other way as well.

**Comment by peteihis** [comment]
And I think I discovered the problem: For example `CreateCubeTool` line 121, 122:

~~~~java
    xdir = xdir.times(1.0/xsize);
    ydir = ydir.times(1.0/ysize);
~~~~

The `xsize` and `ysize` can be 0.0. `CreateSphereTool` and `CreateCylinderTool` share the same structure. In `CreateCurve` tool there is also a line where division by 0 may occur.

I think the lines above mean `xdir.normalize()`, but there still is the problem that `xdir` may be `Vec3(0,0,0)`. It would probably work if the direction vector would use the previous value if the new length is 0 and if one of the sizes were 0, then the just created object were erased at mouse realease.

**Comment by Sailsman63** [comment]
Hmm... I'd think that, if it's otherwise valid for the primitive to have a 0 dimension (there may be some uses for this... Think of a scale track that flattens the object in 1 dimension...), we should figure out how to handle that at creation time.

**Comment by peteihis** [comment]
> we should figure out how to handle that at creation time.

The object is not created before the mouse is dragged. At creation it's probably safe to assume that a 0 dimension is not intentional, at least if the other direction drag-value is only a pixel or two. Setting a dimension on an already existing object 0 is already perfectly legal and it does not damage the (Coordinate system of the) ObjectInfo as it happens in the creation tool.

I think I have sketched (one option for) the procedure out in my mind... I'll be back. :)

**Comment by peastman** [comment]
We definitely should be able to handle objects with size 0.  There are lots of ways to get one, many of which we wouldn't want to block (creating one from a script, having a scale track and letting the scale go to 0, etc.).  Also, meshes routinely have one dimension equal to 0.  We just need to figure out why it's causing the display to mess up and fix it.

**Comment by peteihis** [comment]
There is no general problem in handling objects with a zero for a dimension. This is happens with only primitive and there is no problem in *handling* a primitive with a zero dimension either. 

The problem is specific to the creation tools, where a direction vector of the ObjectInfo becomes (obviously) `Vec3(NaN, NaN, NaN)` or `Vec3(0, 0, 0)`. ... I have found a way to tackle that. 

I would also put there a limit, that the new object will not be created until the mouse is first dragged at least 3 or 4 pixels' worth, x+y combined. Moving just 1 pixel to one or both directions is most likely an accidental hit. This would still allow creating a zerodimesionprimitive by moving the mouse back to where the button was first pressed. _(Unless mouse release checks for 0 dimensions and uses undo, which would comply with the logic of `CreateSplineMesh`: The tool will not create 0-dimensions but you can set a dimension to 0 later.)_

Another thing I found is in the editor dialogs of the primitives:

~~~~java
    ValueField xField = new ValueField(key.x, ValueField.POSITIVE, 5);
~~~~

Somehow typing a 0 or 0.0 into the fields ends up being some other number, but I have no idea how the number was generated. -- Possibly during erasing the previous value. Changing the value field constraint to `NONNEGATIVE` removes that problem too.

For comparison a flat SplineMesh is an entirely different alien: The z-dimension will obviously be 0 but the mesh will not be created if either x or y distance of the mouse drag is 0 pixels. The difference in function is that the `CreateSplineMesh` tool goes to work only _after mouse release_ and during the mouse drag there is no preview of the object itself. The primitive creators again create and add the object to scene at _first mouse drag_ which makes the previewing possible during creation.

I'll push a fix proposal in a couple of days...

**Comment by Sailsman63** [comment]
I've deliberately tried to do a drag w/'0' distance, and I've not been able to duplicate the issue. What platform are you seeing it on?

**Comment by peteihis** [comment]
You are trying too hard :) -- It's a Win10. 

See this screen capture video.

[Zero sized Cube.zip](https://github.com/ArtOfIllusion/ArtOfIllusion/files/3395434/Zero.sized.Cube.zip)

**Comment by peastman** [comment]
Agreed, it should be `NONNEGATIVE` instead of `POSITIVE`.
