### ISSUE TITLE
Two part translation not working correctly

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/ArtOfIllusion#130]
At least this translation, that is split into two parts is not working as it is supposed to. The ´{0}´ is supposed to be the name of the image, that is going to be processed.

![translation_error](https://user-images.githubusercontent.com/22843957/61658912-0f839480-accf-11e9-9478-645b371133ec.jpg)

This is in **Scene / Images... / View Details... / Convert to local** that is used on linked images. Can't say what is wrong yet but should probably double check the other similar cases too.

**Comment by peteihis** [comment]
Found on problem:

~~~~.txt
convertQuestion=Import image '{0}' into the scene
~~~~
needs to be
~~~~.txt
convertQuestion=Import image {0} into the scene
~~~~
but it still thinks that the name if thei ma

**Comment by makiam** [comment]
If need to substituted value to be quoted, the quote character need to be escaped...
>> convertQuestion=Import image ''{0}'' into the scene

**Comment by peteihis** [comment]
Ok. I was trying to use single quotes, but there does not seem to be a good way to handle that in this context (I tried a few things). Normal quotes will do. -- And I found the "unnamed-bug". Posting a fix soon.
