### ISSUE TITLE
Surface text sides inverted

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/ArtOfIllusion#140]
Just recently I noticed, that when you use the Text tool in Surface mode, and put a layered texture on it, Front and Back are opposite to, what you'd expect.

**Comment by peteihis** [comment]
The tool uses `Curve.convertToTriangleMesh()` to make the flat version. I can guess, that the glyph curves are drawn clockwise so the face normal will be minus z. 

Interestingly, for the thickened version the front surface seems to be created exactly in the same order as the first created flat version but the surface normals in the final text are still correct...

**Comment by Sailsman63** [comment]
The thickened version is probably built back-face-first, which leaves the correct normals when finished.

The fix here is almost certainly just calling `invertNormals()` on the surface mesh before returning. Good simple first fix for someone just getting their feet wet.

**Comment by peteihis** [comment]
>  for the thickened version the front surface seems to be created exactly in the same order

I found where the the normal direction is reversed for the other surface.

> invertNormals() 

Added `reverseNormals()` per glyph. Seemed like the most natural place.
