### ISSUE TITLE
Modeling-Mode rotation.

### ISSUE THREAD

**Issue by Sailsman63** [ArtOfIllusion/ArtOfIllusion#148]
Just noticed something:

When editing a triangle mesh, you can hide parts of the mesh so they don't get in your way. If you do so, the center-click to adjust rotation center still triggers on the nearest part of the total mesh, even if that part is hidden.

For some reason,  polymesh behaves better (triggers only on the visible parts of the mesh)

**Comment by peteihis** [comment]
So it does!

At a quick look I did not see an obvious solution or even a reason to why they are different. I have an idea how to try to solve it but let's see where it leads to....

**Comment by peteihis** [comment]
MeshViewers send to CanvasDrawers the information which triangles of the mesh NOT to render as a separate list along with the full RenderingMesh. Only TriangleMesh and PolyMesh actually have this option available. The rest just send `null`.

TriMeshEditorWindow and PolyMeshEditorWindow both have `getHiddenFaces()` which provides the list. I would have assumed that this to be defined in the `FacetedMesh` interface but that was not the case.  Triangle meshes and PolyMeshes should then have a special arrangement in the ClickedPointFinder to handle this feature.

So far I did not get deep enough to tell why PME responds differently from TriMesh though. The hiding is basically handled the same way. PME seems to handle invisibility *also* as an extra texture parameter but ClickedPointFinder has no way of detecting that either.

**Comment by Sailsman63** [comment]
I think I spoke too soon on this.

Sometimes, the MeshViewer (Triangles) behaves well. Sometimes it gets a Weird Idea of where to center the camera rotation. 

I've now been able to reproduce even with the entire mesh visible. Once it gets stuck that way, it seems to need "Fit View to Selection" to recover.

**Comment by peteihis** [comment]
> I think I spoke too soon on this.

Not really. What you found was real and the reason to it was very obvious once I knew where to look.

> ... Weird Idea of where to center the camera rotation.

That must be a different bug. Any idea how to make it happen? 

> Once it gets stuck that way, it seems to need "Fit View to Selection" to recover.

Yeap. The fit views should reset the rotation settings.

**Comment by Sailsman63** [comment]
Frankly, just play with adjusting the center rotation point - center click, rotate a bit, repeat. Maybe add some right-click slide in there. Very inconsistant on what triggers it.

**Comment by peteihis** [comment]
Did you test it witn PolyMesh or TriangleMesh / other core AoI editors?

In case of PME the forced rotation around selection might be a part of it. Should get rid of that feature. I'll try testing anyway

**Comment by Sailsman63** [comment]
No, I was using the Triangle Mesh Editor. PolyMesh seemed to behave the way I was hoping, but I never tried rotating around anything other than a mesh with no selections made.

**Comment by peteihis** [comment]
What about the object? Something complex or more in the cubes and spheres department? Smoothing / display settings? Perspective? What was the weird position of the rotation center? Too close / too far?

I can't get anything strange happening. The only thing coming to my mind is accidentally center clicking a couple of times in a row outside the object, which can set the rotation center pretty far off, but even in that case it is not stuck there. If you see the object again on the screen center clicking on the surface of it gets it back and if you are entirely lost of direction Ctrl+Shit+F finds the objects. 

I do remember that there was a strange situation that you could get yourself into but that was somehow related to switching between the navigation modes and rotating and then some. .... A rare combination anyway. If I remember right, it was found after the UI-change package was merged. I was sometimes able to repeat that then, but was not sure how.

**Comment by Sailsman63** [comment]
I've not seen it yet with simpler meshes, though I've not spent as much time testing them. So far, I've seen it with a fairly dense imported mesh: ~16,000 vertices, ~27,000 faces. 

(It was much harder to reproduce today)

Parallel vs. Perspective does not seem to matter. Mostly in Tray/Space mode, switching between them does not matter so much, AFAICT. Rotation Center seems to get stuck _at_ the camera location, center clicking on the object does not fix. Switching modes does seem to reset. (Not unexpected)

Not sure if this is something that others are experiencing, or If I'm just oversensitive.

**Comment by peteihis** [comment]
> I'll try to build myself a test case...

Did. I was wring above. Used "Lucy".  Vertices/Faces  = 224445/448880. No problem handling that. No NullPointerExceptions (J8 to J8) reported.

Instead I discovered a **concept level bug**: While the coordinates are handled correctly according to the view, visibility is handled as it is set on the SceneViewer, not as in the working view of the ObjectViewer. &rarr; When you mean to click a point on the surface of the object, you may actually be clicking on the surface of _another_ object, that in the scene would be between your viewing direction and the object that you are looking at!

To fix that there is a choice to be made: If "Show Entire Scene" is set, should the point finder react to the other objects or just the one that is open in the editor? Both would be justified, but I'd probably lean towards WYSYWYG here.... 


And now to find, how to separate object viewers from the scene viewer.....

**Comment by Sailsman63** [comment]
Ahhh... that's an interesting one. I'll do some targeted testing, now that I know what to look for.

**Comment by Sailsman63** [comment]
Bingo! Confirmed. Very good catch!

Also, this _does_ affect polymesh as well. Last time I tested it, the test mesh was the only object in the scene. I wonder how many vague "view controls seem odd" reports this one has generated over the years?

**Comment by peteihis** [comment]
Some progress, but still WIP.

There are five different cases that need a slightly different handling, when locating the new rotation center. 
- the scene space (the easy basic case)
- a single object in local coordinates (another basic case), 
- a single object in scene coordinates
- all objects shown in local coordinates
- all object shown in scene coordinates

I've got the others but the single object in scene coordinates is giving me trouble.... And once I get the recipe for that I'll need to do some restructuring. Now there are weird if blocks all over the place.

**Comment by Sailsman63** [comment]
I'm in no rush! Thanks for digging in to this.
