### ISSUE TITLE
Document View Controls

### ISSUE THREAD

**Issue by Sailsman63** [ArtOfIllusion/ArtOfIllusion#154]
The 3.1.0 release contained a major re-work of how viewpoints in the various editors are managed. (Thanks, @peteihis!)

These changes are extensive enough that they really should be documented in the manual

**Comment by Sailsman63** [comment]
I've actually started on this  - Marking the issue self-assigned, so that we don't duplicate effort.

**Comment by peteihis** [comment]
I wonder if this would help. Go 'user_interface' . In it's dedicated file 'mouse_controls'. Pictures of the mouse and the Mac-keyboard are not mine. Thought about modelling a mouse, but I lost the file that I had started.... :/

https://github.com/peteihis/Manual/tree/WIP_311_update/WIP_311_update

I thought the pictures (esp. the 3-button mouse) should be worked into a map where you can see in one glimpse what is where.

**Comment by Sailsman63** [comment]
Thanks for reminding me that this exists!

I think I am taking a bit of a different approach for some of it, but I'll definitely use it as a cross-check to make sure I'm not missing anything vital.

**Comment by peteihis** [comment]
> I think I am taking a bit of a different approach for some of it

Sure. I felt a bit uncomfortable about it. A kind of missing the 'flow' or something...

I still think, that a video tutorial would be in order _(already made a manuscript for one some time ago, but there were things and then there were things....)_. And I may have mentioned: A video tutorial entirely different from the one for Blender that I _tried_ to watch.... Took about 15 minutes to get through the basics, that had taken me less than a minute to figure out myself. -- The guy just seemed to like his own voice too much and got to side tracks on what he thought was 'very important to understand...'
