### ISSUE TITLE
Match polygon drawing tool modifier keys with primitives and spline mesh

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/ArtOfIllusion#156]
In the Polygon tool holding Ctrl draws the polygon filled.

To have consistency with  #128 and #141 I'd suggest to put 'Expand from center' under the Ctrl in Polygon too and move the choice for filled drawing into the dialog. 

The dialog of the polygon tool is probably opened most of the times anyway, when the user wants to draw a polygon, so I'd say the choice would be in an obvious place there. And personally I have recently become to appreciate it very highly that tools that do somehow similar things are handled exactly the same way. (One of the things whose value you notice, when it's missing.)

**Comment by Sailsman63** [comment]
I like consistency...

OTOH, filled/non filled seems like such a natural thing to put under a keyboard shortcut, but I expect that if you are doing multiples, they will all be one or the other...
