### ISSUE TITLE
The DOF Graph drawing

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/ArtOfIllusion#164]
Hi.

As we happened to be in the neighborhood, this old pebble in my shoe caught my attention again. There are a number of things that seem to be a bit off with the DOF Graph.

![DOFGraph](https://user-images.githubusercontent.com/22843957/75925310-2a2b0800-5e71-11ea-9b16-3b71b2fae42e.png)

The image is a scaled up blend of two screen captures. Believe it or not the value it displays is 90°, not e.g. 88,5°. The larger gray disc is the one that is displayed, when the DOF is locked. It is bigger than the active dial but it is slightly misplaced. Further more, in the beginning of the code I find:
~~~~Java
    private static final int SIZE = 64;
    private static final int RADIUS1 = 64;
~~~~
...ehhh... diameter equals radius?

I don't know what has been available at the time the DOF Graph was coded but for now I'd suggest:

- Make it a bit bigger.
- Use an odd value for the sizes, so the center point is in the middle of the middle pixel. The graphs look a lot sharper this way.
- Draw in `Graphics2D` (Use a transparent  `BufferedImage` as canvas)
- Use anti aliased drawing.
- Use the options that draw in double values.
- Use `AffineTransform` to move the 0,0 to the center pixel. This simplifies the rest a lot.
- Consider revising colors, like red(dish) tone for restricting the total range, yellow(ish) for comfort range, green(ish) for the bend angle...(if any color at all, might be too much graphic information.)
- Try to have better separation between the handles of the zones.

Of course mouse event handling would be affected accordingly.

**Comment by Sailsman63** [comment]
I'd be even more ambitious than this - I think bone controls should look more like a combo-tool centered on the point around which the bone rotates. (less any irrelevant move/scale handles, etc.

**Comment by peteihis** [comment]
> combo-tool centered on the point around which the bone rotates.

Do you have an example of such a tool?

The bones can be edited in 3D (which certainly could be improved as well). The graph's job is to support each DOF's numeric control. 

If I got our idea, this would mean 3D-display where you could look at the bone from different angles in it's own coodrtinate system. Displaying/handling the restrictions on that would not be easy. And handles.. You definitely need handles or other grabbing elements to work with a graphic tool.

As we have discussed before, there is a lot that could/should be be done to make living with bones easier but that is an entirely different project. This is not it. Now I'm only talking about a small but as I believe helpful clean-up to a small graphic element.

**Comment by Sailsman63** [comment]
Oh, wait... You're looking at the editing dialog graphics. I was definitely thinking of adjusting in 3d.

... Was tired when I commented yesterday.

**Comment by peteihis** [comment]
> I was definitely thinking of adjusting in 3d.

I see... :D We could learn something from the 3D-Manipulator (As a matter of fact, 3ds Max has a manipulator that has features that could be adapted to 3D-handling of bones. I don't have to see it again, the degrees of freedom map out the needs) And when the day comes I'll ask Mr. YardStick too. He said earlier that he had an idea, how he would like it to work.

But yes: Now just the dialog graph with a good look at the calculations. That could help with further processing as well.
