### ISSUE TITLE
CreateCurveTool drawOverlay() renders only last point multiple times

### ISSUE THREAD

**Issue by makiam** [ArtOfIllusion/ArtOfIllusion#17]
See code lines from 96 to 101
We iterate over clickPoint array but at line 98 pos value always evaluates from clickPoint.lastElement()

**Comment by makiam** [comment]
Possible solutions:
1. Draw only last element so no for loop needed
2. Draw all point nodes
3. Draw all points and highlight the last one

**Comment by Sailsman63** [comment]
Hmm... 

Drawing all nodes may make visualizing the curve structure easier, but may also imply that the various points can be edited, which is not the case.... I'll have to think about that one a bit.

**Comment by Sailsman63** [comment]
After considering this for a bit, I believe that we should draw all of the points. The last one, of course, should be the "active" color. The rest should be the "disabled" color.

**Comment by Sailsman63** [comment]
Fixed in PR #21
