### ISSUE TITLE
GetVersion vs. GetMajorVersion

### ISSUE THREAD

**Issue by Sailsman63** [ArtOfIllusion/ArtOfIllusion#195]
https://github.com/ArtOfIllusion/ArtOfIllusion/blob/c97204f24e4108e0fa0ab4a91b2bee77351d1236/ArtOfIllusion/src/artofillusion/ArtOfIllusion.java#L224-L234

Any thoughts on why the version number is split like this? It's not used internally at all.

So far as I can tell, only SPManager calls the `GetMajorVersion()` variant, and it does not *use* that information at all.

I'm tempted to simplify this, as I've been looking at having the build script pull version tags from the source repository.

**Comment by peteihis** [comment]
The point in AoI major version has been that the format stays unchanged inside one major version. I a kind of like that idea. It's a different thing that there have not been any real releases in a year now, though we have had a lot of bug fixes that IMO should have been put out as official releases as soon as they were

The commercial world has quite commonly given up any major version numbers and gone to just yearly versions. AutoDesk Inventor come as 2019, 2020 and 2021 versions and format compatibility guaranteed inside the yearly version. They make a few bug / feature updates format every year (though on teh discussion forums you can find pretty common complaints that have been floating around for 10 years and have not been fixed.) 

Dassault did Catia V4, Catia V5, Catia V6.... Those are not version numbers, they are product names much like Ford Fiesta and Ford Focus and they had their update and service pack version numbers and I think CV6 started to come as yearly versions too.

The 3.0, 3.1 ... does not seem to have any meaning as we went from 2.9 to 3.0 just because numbers ran out but basically I'd favor keeping some kind of a major/minor system and hopefully have the project be far more trigger happy in making update releases.

**Comment by Sailsman63** [comment]
>The point in AoI major version has been that the *format* stays unchanged inside one major version

But the format has it's own internal incrementing numbering system. 

Normally, a major version change means that the *code* API has changed. (ie, if the major version is the same, plugins should still compile and work.)

I'm more wondering why the version string is constructed in code in two parts, rather than just kept as a single string value.

**Comment by peteihis** [comment]
> Normally, a major version change means that the code API has changed. (ie, if the major version is the same, plugins should still compile and work.)

Ah.... You probably have explained that before.... But so, the 2.9 &rarr; 3.0 should have been 2.9 &rarr; 2.10, .... Which again can be a bit confusing in in some contexts. Then the question is if the format should have been. 2.09 &rarr; 2.10 and then the question is what after 2.99...

A side track.

> But the format has it's own internal incrementing numbering system.

Actually several. There is one per scene but then there are some for objects too (and I don't remember but maybe a few other things?

> I'm more wondering why the version string is constructed in code in two parts, rather than just kept as a single string value.

I see your point... Now it's a kind of a mixed system. 

Basically there is the API version (which, as I have seen, has not been changed for API additions), format version (covering both, scene and objects meaning that the releases with the same number are format compatible in all levels), and the release version that should cover bug fixes and minor changes if the two higher versions are unchanged. It would be logical either for all the levels to have  their dedicated `getXxxx`s or just one version string that anybody who is asking could then slice an dice the way they want.

I don't really have preference to either direction, as long as we can guarantee that two releases with different content will never have the same version marking. 

I have one wish though: Sometimes in the recent years I have posted some experimental or temporary fix-versions on the forum for a lot of different reasons, usually somebody running into a problem that I was able to fix quicly. If there will be an automated system for the versioning I'd appreciate if there were a way of making a manual remark into the version string that tells, where the a side version of that kind (or just an experimental/test version) came from.

**Comment by peteihis** [comment]
> So far as I can tell, only SPManager calls the `getMajorVersion()` variant

But coming to think of it, the use of  `getMajorVersion()` would be that a plugin _could_ easily check if it is compatible with a particular version. If nobody uses it now, who can tell about the future? Actually I coded a version adaptation thing in the DisplayModeIcons (which is available on the forum) but that is just based on a `try` block, not checking the number.

**Comment by Sailsman63** [comment]
>then the question is what after 2.99

2.100 (assuming you have another mini release)

>If there will be an automated system for the versioning I'd appreciate if there were a way of making a manual remark into the version string that tells, where the a side version of that kind (or just an experimental/test version) came from.

The plan is to include the git commit hash and possibly message, as well as how many commits since the last "named" version. So, one if your test builds would looks something like "3.2.0+22-build:<hashgarble>-latestbugfixmessage" (22 commits since 3.2.0) and the next real release would be 3.2 1, or 3.3.0 depending on what kind of changes were involved.

**Comment by peteihis** [comment]
>> then the question is what after 2.99
>2.100 (assuming you have another mini release)

What I meant was that quite often when lists are ordered by version numbers the order goes wrong if the amount of digits changes: `.1, .2, .3 ... .9, .10, .11` is ordered, `.1, .10, .11, .2, .3 ... ` Not likely to be a problem here but that's what happens.

**Comment by Sailsman63** [comment]
>the use of getMajorVersion() would be that a plugin could easily check if it is compatible with a particular version. If nobody uses it now, who can tell about the future? 

Even now, if it works with 3.1, it should continue to work for anything before 4.0 so we still need to parse the version string...
We haven't been good about sticking to that idea in the past...

**Comment by Sailsman63** [comment]
I think that this Is probably best left as two methods for the moment.

Since last discussion, I have added support for embedding the Git commit id in the manifest.
