### ISSUE TITLE
Raytracer UI glitches

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/ArtOfIllusion#198]
There are some unfinished features in the interacion between the RaytraceRenderer and the UI.

For example the Soft Shadows check box is grayed out when anti aliasing is off, but the function is still active bascally just making terrible mess without AA on.

![Soft shadows UI](https://user-images.githubusercontent.com/22843957/87231772-aeaf0980-c3c2-11ea-8263-a4c7f26f6675.png) ![Soft shadows no AA](https://user-images.githubusercontent.com/22843957/87231769-a9ea5580-c3c2-11ea-9fe0-b2f3c63a54eb.png)

Which way should it be? Should switching AA off disable the grayed out functions too or should the disabling be removed from the UI? -- I'd vote for the first mentioned.

Also the Illumination tab seems to have similar issues. At least the widgets on the Tab may or may not be grayed out when no illumination is selected ... And I have a vague feeling that some of those things too might stay active when the UI is grayed.

**Comment by peteihis** [comment]
The question might be, if it were better to write a `refreshUI` method that checks everything every time a sate or selected value of an UI element changes and puts for example the combined value of `(softShadows && antiAlias != 0)` into a variable OR just write local checks to UI launch and to where ever the UI-settings are checked.

The only problem with the Illumination tab seems to be that the states of the UI selections is not checked, when the UI is opened for the first time per session. Otherwise it seems to work fine and changing any one of the selections updates the entire tab.

**Comment by peastman** [comment]
The UI is showing the correct behavior.  When antialiasing is off, soft shadows and similar options really should be turned off.  It's not just that the picture is very noisy.  It also is wrong, because the rays aren't distributed correctly.  It uses stratified sampling to reduce noise, but that assumes you have at least four rays per pixel.  So whenever an option is grayed out, it should be disabled in the raytracer.

**Comment by peteihis** [comment]
I tried to track down where things go wrong. At first it seems a bit funny that in  `RaytraceRenderer.spawnEyeRay()` asks for _"the ray number 4 out of 1"_ from `spawnRay()`. However, things seem to be fine until _"it"_ gets to `getDirectLight()`. 

`getDirectLight()` ignores `antialiasLevel` and the ray number affects `light.findRayToLight()`. Then `findRayToLight()` expects ray number to be -1 when randomization is not wanted, so the fix around line 1810 _(got a few extra comment lines there now)_ is: 

~~~~Java
    if (antialiasLevel == 0)
            distToLight = light.findRayToLight(pos, r, this, -1);
    else .... 
~~~~

Gloss may need a similar study, I'll be back at that.

**Comment by peteihis** [comment]
I think I got this sorted out but something else caught my eye: The renderer seems to be working some 10 to 20 × as hard with randomized gloss rays as it does with soft shadows. Does that sound right? 

This simple test piece (1280 × 960 image) took 1 second with just antialiasing, 9 s with shadows, 2:23 with gloss and 9:29 with both. (1280 × 960 pix image)

[Misray3.zip](https://github.com/ArtOfIllusion/ArtOfIllusion/files/5350480/Misray3.zip)

**Comment by peastman** [comment]
It should depend on the settings.  If a light has a large radius so the shadow tapers gradually, that will take a lot of rays.  With a small radius, it will be a lot faster.  Same for glossy reflections: depending on the settings the reflection can be blurred just a little or a lot.

Shadows are intrinsically cheaper in one respect: they only affect the last level of the ray tree (rays sent to light sources).  Each extra reflected ray may lead to a lot of other rays.

**Comment by Sailsman63** [comment]
I've been playing with the included file a bit. There is only 1 light, so there are only a very few (Relatively speaking) Light Rays.

Also, for a given scene, the load for Soft Shadows should only increase linearly in proportion to the number of Shadow rays,
Where the load for Gloss/Translucency will increase exponentially per number of Gloss Rays. (Probably less than GlossRays^2, due to some of the rays from each generation will be pruned because they don't run into anything.)

**Comment by Sailsman63** [comment]
And when you combine both, they each tend to create a fair amount of noise, and so the antialiasing tends to significantly increase the number of samples it takes, trying to smooth that out.
