### ISSUE TITLE
Probably bad flow for scene loading code...

### ISSUE THREAD

**Issue by makiam** [ArtOfIllusion/ArtOfIllusion#202]
Currently Scene loading code do next things...
0. Create InputStream
1. Check file has prefix AoIScene
2 .if it missed reset file pointer back to start of file
3. try to create GZIPStream
4 if it failed close and reopen input stream as uncompressed
5. Read all other data...

So in case when file HAS prefix but cannot open GZIP Stream the next scene reads will read from start of file and  this will read PREFIX data as scene data.
Looks very odd..

**Comment by Sailsman63** [comment]
This is deliberate. `.aoi` files have always been GZIP-compressed, but the prefix is newer.

Around 2013 or so, the average web browser started peeking inside files, and decompressing them on download.
The prefix was added to prevent the decompression.
Therefore, if it's got the prefix, it *will* be compressed.

**Comment by makiam** [comment]
Another oddity for me is implementation material/texture reading code...
In code I see next phases:
read data from stream
lookup for material/texture class with
check that found class is not null or null
and construct new asset from data

It is clear that fist phase error is not recoverable situation
It is clear that we can create stub texture/material object if somethisng wrong at last phase

Not clear why ClassNotFound exception from ArtOfIllusion.lookup(...) method threats as unrecoverable (and not to construct stub) but next check class to null is recoverable

BTW... as I understand lookupClass method return null only in case when no plugins at all... IMO the lookup result should not depend on plugins amount.

**Comment by Sailsman63** [comment]
Could you reference exact code lines? Talking in generalities is likely to add to misunderstandings.

**Comment by makiam** [comment]
See Scene class lines from line 1270
Line 1282 -> cls = ArtOfIllusion.getClass(classname); this line may throw ClassNotFoundException
Line 1303 -> we catch this and rethrow as IOException. And no material created from this data

Other case on same line -> ArtOfIllusion.getClass(classname) not throw exception but null
Line 1285 we check cls variable to null and throw IOException
Line 1290 -> we catch this and create stub <unreadable> material

About lookupClass method...
We have inconsistent behaviour IMO
When class not found in existed classloaders method throws CNF exception. But when no plugin classloaders we just return null

**Comment by Sailsman63** [comment]
From the history, it feels like the inner `try/catch` was patched in quickly to improve error messages. Might be something to clean-up, but it's low priority compared to a lot of other things on the list.

**Comment by Sailsman63** [comment]
The later set of concerns are better addressed as a code-style issue.
