### ISSUE TITLE
Startup Script execution issue

### ISSUE THREAD

**Issue by makiam** [ArtOfIllusion/ArtOfIllusion#214]
I install Mechanisto.bsh  startup script and this gives me java.lang.NoClassDefFoundError: artofillusion/artofillusion (wrong name: artofillusion/ArtOfIllusion) through script execution.
This prevents application from run as Splash Screen never closed

None of AOI code can be executed from startup script, even this simple:
System.out.println("Say path..." + artofillusion.ArtOfIllusion.APP_DIRECTORY);

but executed when script file extension changed to groovy

**Comment by Sailsman63** [comment]
I can't duplicate. I'm not getting layout changes, but no crash/error.

- What version/build are you running?
- What version of Java?
- Are you getting this on startup, or when trying to run from the script window?

**Comment by makiam** [comment]
Seems this just my development environment issue.
When I build and run app standalone I see no this issue.

The difference I see in this cases is different classpath. Standalone run gives me ArtOfIllusion.jar in classpath but from dev env I see instead path to folder with compiled app classes.
