### ISSUE TITLE
Saving Render Dialog settings

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/ArtOfIllusion#230]
Just wanted to let you know that I'm working on that. Should not take too long.

- Currently the settings of the selected renderer are saved but settings that belong to the dialog, like the image size, are not. 
- Also , I found that when you open a file and use 'Render Immediately' before doing anything else, on the first time the renderer settings are not read from metadata. The second time they are.

**Comment by peteihis** [comment]
A couple of things I ran into:

**#1:** I was hoping to separate `Cancel` and `WindowClosingEvent` so that Cancel would save the settings that the user has just changed and WCE would not. Unfortunately `PanelDialog` is wired with `Cancel  = Esc = WindowClosingEvent != OK`, so to make it happen the UI would have to be rebuild from `BDialog`... Probably not worth the trouble.  

As I have many times felt pretty annoyed because of the lost settings that I already made, when I had to go back and adjust something else, I'll have the dialog save the settings every time you exit it in any available way. Let's see how it works out.

**#2:** I think that changing rendering settings should `LayOutWindow.setModified()` _(and I have a faint feeling that somebody else might have pointed that out too)_.  When changes are done to the Panel settings that is easy but the renderers do not know about the LayoutWindow..... I wonder what would be the best way of making it happen? Add a `getConfigPanel()` to take `parent` as parameter or add an optional `setParent()` method and then have `recordConfiguration()` check if anything had changed? And if that change / addition were to be made, it probably should be added to the `Renderer` interface too?

**Comment by peteihis** [comment]
And the problem with `renderImmediately()` is that it is static. It can be made to read the metadata too but it means that a few other things need to be turned static as well. I don't think that hurts as there is only one rendering happening at a time anyway.

**Comment by Sailsman63** [comment]
Point 1: 
No, cancel and close window should *not* save changed settings. Both of these imply "back out and leave things the way they were before I got in here and started messing with them" 

That comes with being a modal dialog.

I could possibly see there being a separate button for "save these settings for later" ("Apply?" Only active if the settings have been changed.)

Point 2:
I'd agree that it should `setModified`, and possibly add an undo record. For the ways and means, I'll have to look a little closer...

**Comment by peteihis** [comment]
> I could possibly see there being a separate button for "save these settings for later"

Going this would lead to rebuilding the UI entirely -- I have had a few thing in my mind for a while ... But with the buttons only it then should be something like "Save settings", "Reset renderer", "Start Rendering", "Cancel" and it would be a nice idea to have templates available for image size and so on.... And then the UI would start to become quite crowded. --> Make a plugin, "AdvancedRenderSetupDialog"? A different project again. :)
