### ISSUE TITLE
Need help with Linux version

### ISSUE THREAD

**Issue by Lkibbler** [ArtOfIllusion/ArtOfIllusion#256]
Hello Linux people, I do not run Linux myself but on someones advice I installed the linux version on my late 2016 MacBook Pro in an effort to get this program to run on it. it didn't work at all but I am worried about what it might have been installed on my computer and where it put it. If anyone out there has any tips as to where I should look for files that should be removed or assurance that nothing bad will come from leaving them wherever they are, I would be most appreciative.
Thank you 
Lee Kibbler

**Comment by peteihis** [comment]
That was quick... :)

**Comment by Sailsman63** [comment]
I had answered this question over on the SF buglist. It's possible that he didn't get the alert.

**Comment by Lkibbler** [comment]
Hello Sailsman63, I didn't get anything because I haven't been actively involved. I would appreciate it if you could direct me to this "SF buglist " Thank you. I am not at all family;iar with this process and am only here to try to make this one piece of software work on my MacBook.

**Comment by Sailsman63** [comment]
I was referring to your bug report over on sourceforge. https://sourceforge.net/p/aoi/bugs/510/

I posted an answer to this question on 08/16, and thought that perhaps you never got notified of it. If the answer is in any way unclear, please tell us where you are getting confused so we can improve the answer.
