### ISSUE TITLE
Triangle mesh constructor description

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/ArtOfIllusion#290]
Just noticed that something here seems to belong somewhere else:

```Java
  /** The constructor takes three arguments.  v[] is an array containing the vertices.
      faces[][] is an N by 3 array containing the indices of the vertices which define each
      face.  The vertices for each face must be listed in order, such that they go
      counter-clockwise when viewed from the outside of the mesh.  All faces must have a
      consistent vertex order, such that the object has a well defined outer surface.
      This is true even if the mesh does not form a closed surface.  It is an error to
      call the constructor with a faces[][] array which does not meet this condition, and
      the results are undefined.  norm[] contains the normal vector at each vertex.  If
      any element of norm[] is null, flat shading will be used around that vertex. */
```
- The constructors takes only two arguments. (So do the rest of them, but different ones.)
- `norm[]` does not exist here, it appears is the `RenderingMesh` constructor, where it also would have a meaning for shading. We do have `getNormals()`, but that calculates them, they don't exist as a precalculated array.

Some of the method descriptions also for example refer to several methods like `"These methods return...."`. That may work if you read the code, but not when it ends up in the documentation.

**Comment by Sailsman63** [comment]
What file and line#?

**Comment by peteihis** [comment]
I thought I said that on the subject: TriangleMesh ... what ever line first constructor is on. And you can't really miss that text.

**Comment by peastman** [comment]
It's a mystery to me!  I don't recall that TriangleMesh ever had a `norm` argument.  Maybe at some point in the very distant past (as in, before I implemented subdivision surfaces, which would put it in the 1990s)?

**Comment by peteihis** [comment]
I had a look at the old sources. That exact same text appears already on AoI 0.6 and has been unchanged ever since. Outdated already then so obviously much older.
