### ISSUE TITLE
Odd behaviour of window layout saving

### ISSUE THREAD

**Issue by makiam** [ArtOfIllusion/ArtOfIllusion#53]
In current implementation the window layout saves in preferences on widget moving. This will save only the last moved scene window and not saves window layout for every scene separately

**Comment by Sailsman63** [comment]
This is a user-level application preference, not a per-file saved setting. This means that the next time a new Layout window is created, the settings will be applied.

Turing this into a per-file setting would require a file-format change. Can you provide a use-case where this would be desireable?

**Comment by peastman** [comment]
If you did that, what would you do if the scene were opened on a different computer that had a different screen resolution?

**Comment by Sailsman63** [comment]
That's another good reason to keep this as a per-user system setting... Though we could include a check for available screen space, and resize proportionately as necessary.

I'm just not seeing a good reason that you would customize the editor layout on a per-file basis.

**Comment by makiam** [comment]
Well... At least this behaviour need to be documented somehow.

**Comment by Sailsman63** [comment]
Hmm... The question would be: where?

There is currently nothing in the UI that would imply that this change would be saved in the specific file. Perhaps a section of the manual would discuss preferences?
