### ISSUE TITLE
ImplicitSphereTest rounding errors?

### ISSUE THREAD

**Issue by Sailsman63** [ArtOfIllusion/ArtOfIllusion#67]
https://github.com/ArtOfIllusion/ArtOfIllusion/blob/0eddacaab0b8465085da35a45951496b6687206c/Tests/src/artofillusion/object/ImplicitSphereTest.java#L51-L53

In some recent runs of the unit tests (working on fixing the test suite) I just got the following errors:

`[junit] expected:<1.125680191712794> but was:<1.1256157239630205>`
on line 52 and, on a susequent run,
`[junit] expected:<-0.07972279469479109> but was:<-0.07970200347745438>`
on line 51.

This test randomly generates the radii for each test. This looks like rounding/overflow errors to me, but without knowing what the input numbers are, I cannot be sure. The test should at least print `r1` & `r2` values for the test sphere, and `x`, `y` & `z` values for that run of the test method.

**Comment by Sailsman63** [comment]
@peastman I'm looking at setting up github actions to test-compile all PRs as they come in... I'd like to run the test suite when that happens, but this test randomly fails. It looks to me like the allowed delta is a little too small for the math operations involved, (Or perhaps, the test is checking at unrealistic locations? I don't know this part of the system well enough to have an opinion)

So far, on every failure, the coordinates match out to four decimal places...

**Comment by peastman** [comment]
I can see why that test would occasionally fail.  It's using a finite difference approximation for the gradient and comparing it to the analytical gradient.  But right at the edge of the influence radius, the gradient is discontinuous, so the finite difference approximation will be less accurate.  If it happens to pick a random point that's too close to that distance, it will likely fail.

This might be a case where it's best to just hardcode a random number seed for which the test passes.

**Comment by Sailsman63** [comment]
I don't doubt that the discontinuity at the edge of the influence could cause issues, but I don't think that's the whole story here.

I've been picking at this a bit, and I've run across a case where `r` is about `0.01` of the influence radius, the `grad` x component was on the order of 40,000. The difference between that and the estimate was about 8.45, so the value at the query point was at least 850ish. Nowhere near the edge of the influence.

If I understand correctly, The approximation method:

- Samples the field strength at 6 'virtual' points bracketing the query point, one pair for each cardinal direction.
- Compares field strength for each pair, the difference shows which way the field is "sloping," and how steeply.
    - Essentially, these pairs add up to a vector that should point in roughly the same direction, with roughly the same magnitude, as `grad` Why the odd, scaled component-wise comparison? I'd think that actually creating the `Vec3` and then doing some work with `dot()` or `cross()` and `len()` would tend to be more numerically stable...

Re: Query points outside of the influence: should these be special-cased to just check `grad == 0,0,0`? This does seem to be a core property, completely irrespective of the fact that it's special-cased in the implementation.

**Comment by peastman** [comment]
> Why the odd, scaled component-wise comparison?

Strictly speaking, what it's doing is computing a second order finite difference approximation to the derivative along each axis, then comparing it to the analytically computed derivative along that same axis.

**Comment by Sailsman63** [comment]
Okay, get that... 

Why is the error-bar being scaled in relationship to the *point value*? Some of these derivatives scale pretty high. I'd think that delta would make more sense being scaled relative to the expected value of the derivative...

**Comment by peastman** [comment]
Possibly that would be a better way of doing it.
