### ISSUE TITLE
Java Language pathname conflict

### ISSUE THREAD

**Issue by Sailsman63** [ArtOfIllusion/ArtOfIllusion#83]
[`artofillusion.procedural.Module`](https://github.com/ArtOfIllusion/ArtOfIllusion/blob/master/ArtOfIllusion/src/artofillusion/procedural/Module.java) conflicts with the new `Java.lang.Module` class.

Since Fully Qualified pathnames are resolved at _compile time,_ existing binaries compiled with Java 1.8 or earlier will still run, but AOI currently refuses to compile under Java 9.

Since the `Java.lang` package is always imported, we have two choices:

- Use the Fully Qualified Name in every call to `artofillusion.procedural.Module` (messy and verbose, will tend to break as other code is added in the future.)
- Change the Classname for `artofillusion.procedural.Module`. This would be a fairly significant refactor, and an API breaker that affects existing plugins.

**Comment by Sailsman63** [comment]
@peastman do you have a preference on this?

We've had a user on sourceforge who has found that his OS now defaults to java 10, so we do need to work on these compatibility bugs.

I'd personally like the second, but since we've got the API breakage, we'd be looking at moving to 4.0.
Thoughts?

**Comment by peastman** [comment]
Sigh.  Thanks Oracle!

I wonder if we could rename it, but in a way that limits API breakage?  We could keep the `artofillusion.procedural.Module` class, then create a new class that extends it called `artofillusion.procedural.NotAModule` (or something similar).  All subclasses would extend `NotAModule`, but any code that expects them to be a `Module` would still work.  I'm not sure if it's worth the trouble though.

Did you have any ideas for what to rename it to?

**Comment by Sailsman63** [comment]
I like that idea. 

- Deprecate `artofillusion.procedural.Module` This will provide a shortstop for any code that tries to use the FQPN, pushing us to use the new name.
- Commit to a version where we _will_ remove the old code? (4.0, but have some time to work out the implications?

I might consider `artofillusion.procedural.PModule` or `artofillusion.procedural.ProcModule` if we wanted to continue to use the word `module`. Otherwise, I might go with `artofillusion.procedural.Block` for both "block of functionality" and "building block" from the visual editor standpoint.

I don't think it will be too hard. My test build only fussed about 20ish uses in the core code (though, I don't doubt there are probably a few more)

**Comment by peastman** [comment]
How about `ProcedureModule`?  Given that all its subclasses have names ending in "Module", I wouldn't want to change it to anything totally different.  And there are already a few other classes that start with "Procedure", so that's consistent with them.

"Find usages" in IDEA reports 162 usages.  It can fix all of them automatically when renaming the class.

**Comment by makiam** [comment]
This breaks at least next plugins: RGBToHSV, SVGTranslator, EqualityModule, VideoMediaFrame....
Also this breaks polymesh export to wawefront Obj code but as we have polymesh code it can be fixed easily

**Comment by Sailsman63** [comment]
@makiam, that's why we considering deprecating `artofillusion.proceedural.Module` rather than removing it. Existing (compiled) plugins will still run, we just won't be able to update/recompile until we update the code.

**Comment by Sailsman63** [comment]
@makiam Okay, I get why the `RGBtoHSV`, `EqualityModule` & `VideoMediaFrame` would have issues (BTW, `VideoMediaFrame` relies on the JMF framework, which I don't think anyone has used in years... needs to be re-written anyway.

`SVGTranslator`, though, Should have nothing to do with the module system (It _imports_ SVG paths to AOI curves)

**Comment by makiam** [comment]
I see through decompiler tool... Translator imports svg gradient fills as 2d ProceduralTexture
