### ISSUE TITLE
SearchListsClassLoader usage

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/ArtOfIllusion#97]
At startup System.out gets lines like:

~~~~txt
klo 13.09.46 [main] in SearchlistClassLoader.findResource() (SearchlistClassLoader.java:442)
   findResource: looking in artofillusion.util.SearchlistClassLoader@6986852 for artofillusion/PluginRegistry.groovy

.....

klo 13.09.46 [main] in SearchlistClassLoader.findResource() (SearchlistClassLoader.java:442)
   findResource: looking in artofillusion.util.SearchlistClassLoader@3d121db3 for Script1$1Customizer.groovy
~~~~

Lines 58 to 371in that case.

I'm not sure what is supposed to happen there, but it seems, that SriptRunner is looking for a set of groovy files in the code structure, that obviously aren't there. On top of that it is set to report the "looking for" but not if the file was found or not.

This is probably a minor issue from the user's point of view, but it doesn't seem right either. Can the line 442 in SearchlistClassLoader at least be commented out?

**Comment by peteihis** [comment]
This did no occur with the latest HEAD.

**Comment by Sailsman63** [comment]
This is just `SearchListClassLoader` being talkative. It tends to log all of it's thoughts out loud as it searches for various class resources. The order in which it searches depends on exact details of your installation, and what plugins are installed, etc.

Don't worry about it looking in what humans would consider "nonsensical" locations. It literally looks through _all_ plugin locations that it has not yet searched until it finds what it needs.

**Comment by peteihis** [comment]
I was not worried about it looking into everywhere but I find it rather annoying that it chooses to report all the places it' is looking at. That looks more like development like debugging to me. I'd suggest to comment out that one line and have it just to report if a particular bit was found or not.
