### ISSUE TITLE
Cannot load scene from file

### ISSUE THREAD

**Issue by neoedmund** [ArtOfIllusion/ArtOfIllusion#98]
I'm the first time trying ArtOfIllusion.
Cannot load scene from file download from http://www.artofillusion.org/artgallery .
It seems scene file is saved using Java Object serialization but over times many objects are just refactoried and package-changed, make it fail to load.
Maybe could use a more reliable format to save .aoi files?

**Comment by peteihis** [comment]
Whics files were the ones with problems and which AoI version are you using?

I just checked and all the available 11 files open without any problems at least on AoI 3.0.3. I don't think that many of those even require any plugins to open. Tht typical one you migh need at first would be the PolyMesh.

It is true, that the format has been evolving over the years, but full backward comatibility is built in. The data content of the files is specific to AoI like it would be on any software, so the saving format needs to be somehow specific to it any way.

**Comment by neoedmund** [comment]
I confirmed the situation is caused by `Plugins/` dir not copied when I run from source. 
With plugins, the .aoi files loaded successfully.
I found this software is unique and great, and I love to play it more :)
Thank you for the hints.

**Comment by peteihis** [comment]
Glad you got it workin.

I did'n think of that but some parts of the 'core sofrware' are actually implemented as plugins and those naturally should be present.

**Comment by neoedmund** [comment]
By the way, where are the source code of the plugins, are they all open-sourced?

**Comment by makiam** [comment]
Some plugins sources avaliable here on Github: https://github.com/ArtOfIllusion. (SPManager, Polymesh, Hologram and TaPD)
Also You can take a look at this sourceforge repository: https://sourceforge.net/projects/aoisp/

**Comment by peteihis** [comment]
The https://sourceforge.net/projects/aoisp/ is where the Scripts and Plugins Manager retrieves the plugins from. (Should be in Tools menu, the bottom most item. The SPM itself is also a plugin.)

Unfortunately not nearly all of the plugins have their sources available. It was discussed some time ago, that in future it should be made a requirement to all the new content in the repository that it should be open sourced. (If someone wants to keep their plugins to themselves, they of course are free to do so.)

**Comment by Sailsman63** [comment]
>I confirmed the situation is caused by Plugins/ dir not copied when I run from source.

How, exactly, did you build from source? The core build script should create the `/Plugins` directory. 
It does not, however, try to copy existing plugins from a separate, standard AOI installation.

**Comment by neoedmund** [comment]
> > I confirmed the situation is caused by Plugins/ dir not copied when I run from source.
> 
> How, exactly, did you build from source? The core build script should create the `/Plugins` directory.
> It does not, however, try to copy existing plugins from a separate, standard AOI installation.

I created new project in Eclipse, It simply compiles and runs but warned that something plugins directory are not present.

**Comment by Sailsman63** [comment]
Ahh... Eclipse, by default, uses its own internal project build mechanism. It does not know how to build AOI correctly. AOI is built using a custom ant script, which Eclipse can access. Check Eclipse documentation for details.

If you'd like more detail about how AOI is usually built, please see the file docs/Building.md
